name: Generate Changelog

on:
    schedule:
        - cron: '0 13 * * 0'
    workflow_dispatch:

jobs:
    changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Python
              uses: actions/checkout@v3

            - name: Checkout repository
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run changelog script
              env:
                GH_TOKEN: ${{ secrets.REPOLINTER_AUTO_TOKEN }}
              run: python generate_changelog.py