name: Generate Changelog

on:
    schedule:
        - cron: '0 13 * * 0'
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  generate-weekly-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Generate weekly changelog
        env:
          GH_TOKEN: ${{ secrets.REPOLINTER_AUTO_TOKEN }}
        run: |
          python scripts/generate_changelog_weekly.py
      
      - name: Generate summary
        run: |
          python scripts/generate_summary.py

      - name: Create Pull Request with Summary
        env: 
          GH_TOKEN: ${{ secrets.REPOLINTER_AUTO_TOKEN }}
        run: |
          # Get latest summary files
          TIMESTAMP=$(date +"%Y-%m-%d")
          PR_TITLE_FILE="changelog_data/summaries/pr_title_TIMESTAMP.txt"
          PR_BODY_FILE="changelog_data/summaries/pr_body_TIMESTAMP.md"

          if [ ! -f "$PR_TITLE_FILE" ] || [ ! -f "$PR_BODY_FILE" ]; then
            echo "Summary not found, checking latest file..."
            PR_TITLE_FILE=$(ls -t changelog_data/summaries/pr_title_*.txt 2>/dev/null | head -n1)
            PR_BODY_FILE=$(ls -t changelog_data/summaries/pr_body_*.md 2>/dev/null | head -n1)
          fi

          if [ -f "$PR_TITLE_FILE" ] && [ -f "$PR_BODY_FILE" ]; then
            PR_TITLE=$(cat "$PR_TITLE_FILE")

            BRANCH_NAME="weekly-changelog-$(date +"%Y-%m-%d")"

            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git config --global pull.rebase true

            if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
              git fetch origin "$BRANCH_NAME"
              git checkout "$BRANCH_NAME"
              git pull origin "$BRANCH_NAME"
            else
              git checkout -b "$BRANCH_NAME"
            fi

            git add changelog_data/
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit"
            else
              git commit -sm "Add weekly changelog summary for $(date +"%Y-%m-%d")"
            fi

            for i in 1 2 3; do
              git pull --rebase origin "$BRANCH_NAME"
              if git push origin "$BRANCH_NAME"; then
                break
              fi
              sleep 5
            done

            # git commit -sm "Add weekly changelog summary for $(date +"%Y-%m-%d")" || echo "No changes to commit"
            # git push origin "$BRANCH_NAME"

            if ! gh pr view "$BRANCH_NAME" --json number 2>/dev/null; then
              gh api repos/${{ github.repository }}/labels -f name='changelog' -f color='0E8A16' || true
              gh api repos/${{ github.repository }}/labels -f name='automated' -f color='FB04D4' || true

              gh pr create \
                --title "$PR_TITLE" \
                --body-file "$PR_BODY_FILE" \
                --base main \
                --head "$BRANCH_NAME" \
                --label "changelog,automated" || \
                gh pr create \
                --title "$PR_TITLE" \
                --body-file "$PR_BODY_FILE" \
                --base main \
                --head "$BRANCH_NAME"
            else
              echo "PR already exists for $BRANCH_NAME"
            fi
          else
            echo "Could not find PR title or body files"
            exit 1
          fi
      
      - name: Upload summary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-changelog-summary
          path: |
            changelog_data/summaries/
            changelog_data/data/weekly_changelog_*.json
